version: '2'
services:
  nginx:
    image: nginx:1.9.6
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    volumes_from:
      - restler

  restler:
    build:
      context: .
    volumes: 
      - ./:/var/www/html/restler
